services:
  apiservice:
    image: apiservice
    ports:
      - "5044:8080"
    build:
      context: ApiService
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    networks:
      - plantingpad_network
  authservice:
    image: authservice
    ports:
      - "5045:8080"
    build:
      context: AuthService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    networks:
      - plantingpad_network
  db:      
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: sqlserver
    ports:
      - "1533:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    networks:
      - plantingpad_network
    volumes:
      - dbdata:/var/opt/mssql

networks:
  plantingpad_network:
    
volumes:
  dbdata:
        